# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Session-YieldCC
version:      0.10
version_from: lib/POE/Session/YieldCC.pm
installdirs:  site
requires:
    Coro:                          1.11
    POE:                           0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
